# Generated by Django 5.2.4 on 2025-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stara_cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='proizvodi/')),
            ],
        ),
    ]
