# Generated by Django 5.2.4 on 2025-07-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_grupaproizvoda_proizvod_grupa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvod',
            name='stara_cena',
        ),
    ]
