# Generated by Django 5.2.4 on 2025-07-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_proizvod_stara_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='grupa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proizvodi', to='shop.grupaproizvoda'),
        ),
    ]
