# Generated by Django 5.2.4 on 2025-08-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_proizvod_grupa"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Proizvod",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="GrupaProizvoda",
            new_name="ProductGroup",
        ),
    ]
