# Generated by Django 5.2.4 on 2025-09-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_proizvod_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="opis",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="naziv",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="cena",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="productgroup",
            old_name="naziv",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="grupa",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slika",
        ),
        migrations.AddField(
            model_name="product",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.productgroup",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
